version: '3.8'

networks:
  microservico-net:

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - microservico-net

  microservico-cliente:
    build:
      context: .
      dockerfile: MicroservicoCliente/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - rabbitmq
    networks:
      - microservico-net

  microservico-servidor:
    build:
      context: .
      dockerfile: MicroservicoServidor/Dockerfile
    ports:
      - "5002:80"
    depends_on:
      - rabbitmq
    networks:
      - microservico-net
